Repository Rosa-Luxemburgstiftung-Berlin/ansible-opnsense, pull requests merged in 2024-05, with the labels that each got.

#71 Fix encalg and hashalg update
  .github/workflows/test.yml
  tasks/ipsecphase2.yml
  test/ipsec-test1-04-encalg-expect.xml
  test/ipsec-test1-04-encalg.xml
  test/ipsec-test1-04-encalg.yml
  test/test.yml
Labels: bug, ready for merge

#72 implemented tests for pr #67
  test/ipsec-test1-deconfigure-p2-expect.xml
  test/ipsec-test1-deconfigure-p2.xml
  test/ipsec-test1-deconfigure-p2.yml
Labels: enhancement

#67 Add tasks to clean unconfigured P2s
  tasks/ipsecphase1.yml
Labels: enhancement, ready for merge, test required

#64 issue63 openvpn instances
  defaults/main.yml
  handlers/main.yml
  tasks/main.yml
  tasks/openvpn.yml
  tasks/openvpninstance.yml
  tasks/openvpnoverwrite.yml
  tasks/openvpnstatickey.yml
  tasks/vpn.yml
  test/filter-testifaceunsorted-expect.xml
  test/openvpn-testcfg-expect.xml
  test/openvpn-testcfg.xml
  test/openvpn-testcfg.yml
  test/test.yml
Labels: enhancement, ready for merge
