Repository Rosa-Luxemburgstiftung-Berlin/ansible-opnsense, pull requests merged in 2024-09, with the labels that each got.

#97 task288 - add dyndns tasks,test,handler
  handlers/main.yml
  tasks/dyndns.yml
  tasks/main.yml
  test/dyndns-test-expect.xml
  test/dyndns-test.xml
  test/dyndns-test.yml
  test/test.yml
Labels: enhancement, test required

#96 unboundplus tasks and tests
  defaults/main.yml
  handlers/main.yml
  tasks/unbound.yml
  tasks/unboundaclsrows.yml
  tasks/unboundplus.yml
  tasks/unboundplusuuid.yml
  test/Readme.md
  test/test.yml
  test/testsimpletask.yml
  test/unbound-test-acl-expect.xml
  test/unbound-test-acl.xml
  test/unbound-test-acl.yml
  test/unbound-test-overrides-expect.xml
  test/unbound-test-overrides.xml
  test/unbound-test-overrides.yml
  test/unbound-test1-expect.xml
  test/unbound-test1.xml
  test/unbound-test1.yml
  test/unbound-test2-expect.xml
  test/unbound-test2.xml
  test/unbound-test2.yml
Labels: bug

#102 custom configd actions
  handlers/main.yml
  tasks/configd.yml
  tasks/cron.yml
  tasks/main.yml
  templates/configd_action.j2
Labels: enhancement
