Repository Rosa-Luxemburgstiftung-Berlin/ansible-opnsense, pull requests merged in 2024-12, with the labels that each got.

#112 Add zabbix agent configuration
  handlers/main.yml
  tasks/main.yml
  tasks/zabbixagent.yml
  tasks/zabbixagentuserparameters.yml
Labels: enhancement

#116 fix ansible python interpreter 4 test workflow
  .github/workflows/test.yml
Labels: bug

#114 issue #113 - fix xml encoding
  README.md
  defaults/main.yml
  scripts/opn-xml-fix-encoding.php
  tasks/main.yml
Labels: enhancement, ready for merge
